# Generated by Django 3.0 on 2020-03-25 01:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=['title', 'published__year'], unique_with=['title', 'published__day']),
        ),
    ]
